chore: docs
bcgov/sso-keycloak pull request #321
Opened 2023-11-22 23:16 UTC by jlangy

- Cloned our wiki content into a /wiki folder
- Adding config files for mkdocs

I copied catalog-info from the example and update relavent keys, will have to check with devhub team if any config needs to change, I couldn't find good documentation on how the deploy process fully works. But this serves the content well locally with `mkdocs serve` so should be able to build fine

2023-11-24 21:02 UTC, sheaphillips requested changes

2023-11-24 21:19 UTC, sheaphillips requested changes

2023-11-24 21:19 UTC, sheaphillips commented on mkdocs.yml
> +plugins:
You'll want to update the mkdocs.yml file to include references to the needed plugins:


```
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
```

2023-12-20 21:31 UTC, jenreiher-bcgov commented on catalog-info.yaml
> +  description: "A guide to the BC Gov Common Hosted Single Sign-on"
Please add a title here so that the main techdocs page (http://mvp.developer.gov.bc.ca/docs) is more human readable. e.g. `title: "Keycloak SSO Docs"`

2024-01-12 19:07 UTC, thegentlemanphysicist commented on wiki/Are-you-part-of-the-GitHub-BC-Gov-Org.md
> +You have been redirected to this page because your github account is not affiliated with the organization `bcgov`.
Has the redirect link been fixed?

2024-01-12 19:31 UTC, thegentlemanphysicist approved these changes

2024-01-12 20:53 UTC, merged